# Generated by Django 5.1.1 on 2024-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(unique=True),
        ),
    ]
