# Generated by Django 5.1.1 on 2024-09-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_addasset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaceasset',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='replaceasset',
            name='meta_data',
        ),
        migrations.RemoveField(
            model_name='replaceasset',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('APP', 'Approved'), ('REJ', 'Rejected')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset', to='api.asset'),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeasset',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
