# Generated by Django 5.1.1 on 2024-09-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_replaceasset_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeasset',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset', to='api.asset'),
        ),
    ]
