# Generated by Django 5.1.1 on 2024-09-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employeeasset_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='meta_data',
        ),
    ]
